//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 14.0.23107.0
// 
namespace MyApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MaslataSoap")]
    public interface MaslataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<MyApp.ServiceReference1.CustomerLoginResponse> CustomerLoginAsync(MyApp.ServiceReference1.CustomerLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerRequists", ReplyAction="*")]
        System.Threading.Tasks.Task<MyApp.ServiceReference1.CustomerRequistsResponse> CustomerRequistsAsync(MyApp.ServiceReference1.CustomerRequistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PrintDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> PrintDocAsync(int RequestID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerLogin", Namespace="http://tempuri.org/", Order=0)]
        public MyApp.ServiceReference1.CustomerLoginRequestBody Body;
        
        public CustomerLoginRequest() {
        }
        
        public CustomerLoginRequest(MyApp.ServiceReference1.CustomerLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NationalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public CustomerLoginRequestBody() {
        }
        
        public CustomerLoginRequestBody(string NationalID, string Password) {
            this.NationalID = NationalID;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyApp.ServiceReference1.CustomerLoginResponseBody Body;
        
        public CustomerLoginResponse() {
        }
        
        public CustomerLoginResponse(MyApp.ServiceReference1.CustomerLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerLoginResult;
        
        public CustomerLoginResponseBody() {
        }
        
        public CustomerLoginResponseBody(string CustomerLoginResult) {
            this.CustomerLoginResult = CustomerLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerRequistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerRequists", Namespace="http://tempuri.org/", Order=0)]
        public MyApp.ServiceReference1.CustomerRequistsRequestBody Body;
        
        public CustomerRequistsRequest() {
        }
        
        public CustomerRequistsRequest(MyApp.ServiceReference1.CustomerRequistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerRequistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerID;
        
        public CustomerRequistsRequestBody() {
        }
        
        public CustomerRequistsRequestBody(string CustomerID) {
            this.CustomerID = CustomerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerRequistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerRequistsResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyApp.ServiceReference1.CustomerRequistsResponseBody Body;
        
        public CustomerRequistsResponse() {
        }
        
        public CustomerRequistsResponse(MyApp.ServiceReference1.CustomerRequistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerRequistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CustomerRequistsResult;
        
        public CustomerRequistsResponseBody() {
        }
        
        public CustomerRequistsResponseBody(string CustomerRequistsResult) {
            this.CustomerRequistsResult = CustomerRequistsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaslataSoapChannel : MyApp.ServiceReference1.MaslataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaslataSoapClient : System.ServiceModel.ClientBase<MyApp.ServiceReference1.MaslataSoap>, MyApp.ServiceReference1.MaslataSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MaslataSoapClient() : 
                base(MaslataSoapClient.GetDefaultBinding(), MaslataSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.MaslataSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaslataSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(MaslataSoapClient.GetBindingForEndpoint(endpointConfiguration), MaslataSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaslataSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MaslataSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaslataSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MaslataSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MaslataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyApp.ServiceReference1.CustomerLoginResponse> MyApp.ServiceReference1.MaslataSoap.CustomerLoginAsync(MyApp.ServiceReference1.CustomerLoginRequest request) {
            return base.Channel.CustomerLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyApp.ServiceReference1.CustomerLoginResponse> CustomerLoginAsync(string NationalID, string Password) {
            MyApp.ServiceReference1.CustomerLoginRequest inValue = new MyApp.ServiceReference1.CustomerLoginRequest();
            inValue.Body = new MyApp.ServiceReference1.CustomerLoginRequestBody();
            inValue.Body.NationalID = NationalID;
            inValue.Body.Password = Password;
            return ((MyApp.ServiceReference1.MaslataSoap)(this)).CustomerLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyApp.ServiceReference1.CustomerRequistsResponse> MyApp.ServiceReference1.MaslataSoap.CustomerRequistsAsync(MyApp.ServiceReference1.CustomerRequistsRequest request) {
            return base.Channel.CustomerRequistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyApp.ServiceReference1.CustomerRequistsResponse> CustomerRequistsAsync(string CustomerID) {
            MyApp.ServiceReference1.CustomerRequistsRequest inValue = new MyApp.ServiceReference1.CustomerRequistsRequest();
            inValue.Body = new MyApp.ServiceReference1.CustomerRequistsRequestBody();
            inValue.Body.CustomerID = CustomerID;
            return ((MyApp.ServiceReference1.MaslataSoap)(this)).CustomerRequistsAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> PrintDocAsync(int RequestID) {
            return base.Channel.PrintDocAsync(RequestID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.MaslataSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.MaslataSoap)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:58355/Maslata.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return MaslataSoapClient.GetBindingForEndpoint(EndpointConfiguration.MaslataSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return MaslataSoapClient.GetEndpointAddress(EndpointConfiguration.MaslataSoap);
        }
        
        public enum EndpointConfiguration {
            
            MaslataSoap,
        }
    }
}
